name: Update Docs

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"

jobs:
  update:
    name: Update Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        artifact:
        - access-widener
        - dev-launch-injector
        - lorenz-tiny
        - procyon-quilt-compilertools
        - procyon-quilt-core
        - procyon-quilt-expressions
        - procyon-quilt-reflection
        - quilt-loader
        - quilt-loom
        - sponge-mixin
        - sponge-mixin-compile-extensions
        - tiny-mappings-parser
        - tiny-reampper
        - yarn
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Update docs
        run: |
          rm -rf ./docs/${{ matrix.artifact }}/
          mkdir -p ./docs/${{ matrix.artifact }}
          cd ./docs/${{ matrix.artifact }}

          curl -sL "https://maven.quiltmc.org/service/rest/v1/search/assets/download?repository=release&group=org.quiltmc&name=${{ matrix.artifact }}&maven.classifier=javadoc&sort=version" -o ${{ matrix.artifact }}.jar
          unzip ${{ matrix.artifact }}.jar
          rm ${{ matrix.artifact }}.jar
      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          default_author: github_actions
          message: Update ${{ matrix.artifact }} docs
          push: true
          signoff: true
